#!/bin/bash
#
# bootstrap installs things.

function installScript() {	
	# sudo -v #ask password beforehand
	source ~/.dotfiles/installscript
}

function preInstallScript() {
	source ~/.dotfiles/pre-installscript
}

function installWorkApplications() {
	source ~/.dotfiles/macos/work-app.sh
}

function installMASApplications() {
	source ~/.dotfiles/macos/mas-app.sh
}

function installAdditionnalApplications() {
	source ~/.dotfiles/macos/additionnal-app.sh
}

function installSymbolicLinks() {
	source ~/.dotfiles/macos/set-defaults.sh
}

function runOSXModifications() {
	sudo -v #ask password beforehand
	source ~/.dotfiles/macos/set-defaults.sh
}

	cat <<'TITLE'

██████╗  ██████╗ ████████╗███████╗██╗██╗     ███████╗███████╗
██╔══██╗██╔═══██╗╚══██╔══╝██╔════╝██║██║     ██╔════╝██╔════╝
██║  ██║██║   ██║   ██║   █████╗  ██║██║     █████╗  ███████╗
██║  ██║██║   ██║   ██║   ██╔══╝  ██║██║     ██╔══╝  ╚════██║
██████╔╝╚██████╔╝   ██║   ██║     ██║███████╗███████╗███████║
╚═════╝  ╚═════╝    ╚═╝   ╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝
                                                             
TITLE

finished=false
while [[ "$finished" != true ]]; do
	cat <<'TITLE'
                                                            
█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗
╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝
                                                            
TITLE
	echo 'Choose an item for more informations'
	echo '------------------------------------'
	echo '1. Pre-install script'
	echo '2. Install script'
	echo '3. Install work applications'
	echo '4. Install MAS applications'
	echo '5. Install Additionnal applications'
	echo '6. Symbolic links of rc files'
	echo '7. OSX defaults modifications'
	echo "8. Fix Oh-my-Zsh's rights"
	echo '0. Quit'
	echo '------------------------------------'
	read -p 'Choose number : ' menu
	echo '------------------------------------'

	case $menu in
		1)
			echo 'This script will install iTerm2 and switch to it.'
			read -p 'Install iTerm2? [y/n] : ' reply
			
			if [[ $reply =~ ^[Yy]$ ]]
			then
				preInstallScript    
			fi
		;;
		2)
			echo 'This script will install the following :'
			echo ' - Oh-my-zsh'
			echo ' - Homebrew'
			echo ' - node 10'
			echo ' - pkg-config'
			echo ' - wget'
			echo ' - composer'
			echo ' - vim'
			echo ' - hub'
			echo ' - quicklock plugins'
			echo ' - php'
			echo ' - imagick'
			echo ' - xdebug'
			echo ' - redis'
			echo ' - Laravel Valet'
			echo ' - MariaDB'
			echo ' - Yarn'
			echo ' - Mackup'
			echo ' - zsh-autosuggestions'
			echo ' - Usefull CLI Tools (curl htop nmap links geoip watch ffmpeg speedtest-cli tldr jq wifi-password youtube-dl gnupg libpng jpeg highlight ssh-copy-id)'

			echo '----------------------------'
			read -p 'Install everything? [y/n] : ' reply
			echo '----------------------------'

			if [[ $reply =~ ^[Yy]$ ]]
			then
				installScript    
			fi
		;;
		3)
			echo 'This script will install the following :'
			
			echo ' - Visual Studio Code'
			echo ' - Slack'
			echo ' - Virtualbox'
			echo ' - Vagrant'
			echo ' - Tinkerwell'
			echo ' - Spectacle'
			echo ' - Postman'
			echo ' - Google Chrome'
			echo ' - Sequel Ace'
			echo ' - Dropbox'
			echo ' - Keka'
			echo ' - Notion'
			echo ' - Bitwarden'
			echo ' - F.lux'
			echo ' - Spotify'

			echo '----------------------------'
			read -p 'Install everything? [y/n] : ' reply
			echo '----------------------------'
			
			if [[ $reply =~ ^[Yy]$ ]]
			then
				installWorkApplications    
			fi
		;;
		4)
			echo 'This script will install the following :'
			echo ' - Mac Apple Store CLI'
			echo ' - Bear'
			echo ' - Spark'

			echo '----------------------------'
			read -p 'Install everything? [y/n] : ' reply
			echo '----------------------------'
			
			if [[ $reply =~ ^[Yy]$ ]]
			then
				installMASApplications    
			fi
		;;
		5)
			echo 'This script will install the following :'
			echo ' - httpie'
			echo ' - ack'
			echo ' - doctl'
			echo ' - phpunit-watcher'
			echo ' - Mixed Content Scannerl CLI (Spatie)'
			echo ' - GhostScript'
			echo ' - Skype'
			echo ' - Termius'
			echo ' - Opera'
			echo ' - Firefox'
			echo ' - FortiClient'
			echo ' - Alfred'
			echo ' - GrandPerspective'

			echo '----------------------------'
			read -p 'Install everything? [y/n] : ' reply
			echo '----------------------------'
			
			if [[ $reply =~ ^[Yy]$ ]]
			then
				installAdditionnalApplications    
			fi
		;;
		6) 
			echo 'This script will create symbolic links for rc files with pre-build configuration'

			echo ' - .global-gitignore'
			echo ' - .zshrc'
			echo ' - .vimrc'
			echo ' - .vim'
			echo ' - .yarnrc'
			echo ' - .mackup.cfg'
			echo ' - iterm2.plist'
			echo ' - chmod z.sh'
			echo '------------------------------'
			read -p 'Create symbolic links? [y/n] : ' reply
			echo '------------------------------'
			
			if [[ $reply =~ ^[Yy]$ ]]
			then
				installSymbolicLinks
			fi
		;;
		7)	
			echo 'This script will change OSX defaults'
			echo 'I invite you to go see the documentations for more informations'

			echo '----------------------------'
			read -p 'Change OSX defaults? [y/n] : ' reply
			echo '----------------------------'
			
			if [[ $reply =~ ^[Yy]$ ]]
			then
				runOSXModifications    
			fi
		;;
		8)
			echo '----------------------------'
			read -p "Fix oh-my-zsh's rights? [y/n] : " reply
			echo '----------------------------'
			
			if [[ $reply =~ ^[Yy]$ ]]
			then
				# Remove bad access to zsh
				compaudit | xargs chmod g-w,o-w    
			fi
        ;;
		0 | *)
			finished=true
			cat <<'TITLE'
			
███████╗███████╗███████╗    ██╗   ██╗ ██████╗ ██╗   ██╗       ██╗     
██╔════╝██╔════╝██╔════╝    ╚██╗ ██╔╝██╔═══██╗██║   ██║    ██╗╚██╗    
███████╗█████╗  █████╗       ╚████╔╝ ██║   ██║██║   ██║    ╚═╝ ██║    
╚════██║██╔══╝  ██╔══╝        ╚██╔╝  ██║   ██║██║   ██║    ▄█╗ ██║    
███████║███████╗███████╗       ██║   ╚██████╔╝╚██████╔╝    ▀═╝██╔╝    
╚══════╝╚══════╝╚══════╝       ╚═╝    ╚═════╝  ╚═════╝        ╚═╝     
                                                                      
███╗   ██╗███████╗██╗  ██╗████████╗    ████████╗██╗███╗   ███╗███████╗
████╗  ██║██╔════╝╚██╗██╔╝╚══██╔══╝    ╚══██╔══╝██║████╗ ████║██╔════╝
██╔██╗ ██║█████╗   ╚███╔╝    ██║          ██║   ██║██╔████╔██║█████╗  
██║╚██╗██║██╔══╝   ██╔██╗    ██║          ██║   ██║██║╚██╔╝██║██╔══╝  
██║ ╚████║███████╗██╔╝ ██╗   ██║          ██║   ██║██║ ╚═╝ ██║███████╗
╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝   ╚═╝          ╚═╝   ╚═╝╚═╝     ╚═╝╚══════╝
                                                                      
TITLE
		;;
	esac
done
