#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo '-----------------'
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
# Remove bad access to zsh
compaudit | xargs chmod g-w,o-w

echo '----------------'
echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

echo '------------'
echo 'Install node'
echo '------------'
brew install node@10

echo '------------------'
echo 'Install pkg-config'
echo '------------------'
brew install pkg-config

echo '------------'
echo 'Install wget'
echo '------------'
brew install wget

echo '----------------'
echo 'Install composer'
echo '----------------'
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e5325b19b381bfd88ce90a5ddb7823406b2a38cff6bb704b0acc289a09c8128d4a8ce2bbafcd1fcbdc38666422fe2806') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/local/bin/composer

echo '-----------'
echo 'Install Vim'
echo '-----------'
brew install vim

echo '-----------'
echo 'Install hub'
echo '-----------'
brew install hub

echo 'Install brew cask completion'
brew install brew-cask-completion

echo '-----------------------------------'
echo 'Install some nice quicklook plugins'
echo '-----------------------------------'
brew install betterzip
brew cask install --force qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv webp-quicklook suspicious-package

echo '-----------'
echo 'Install php'
echo '-----------'
brew install php@7.2
brew install php@7.3
brew install php@7.4

brew tap exolnet/homebrew-deprecated
brew install php@7.0
brew install php@7.1

echo '-------------------'
echo 'Install imagemagick'
echo '-------------------'
brew install imagemagick
pecl install imagick
brew services restart php

echo '--------------'
echo 'Install xdebug'
echo '--------------'
pecl install xdebug

echo '-------------'
echo 'Install redis'
echo '-------------'
pecl install redis

echo '---------------------'
echo 'Install Laravel Valet'
echo '---------------------'
composer global require laravel/valet
~/.composer/vendor/bin/valet install

echo '---------------'
echo 'Install MariaDB'
echo '---------------'
brew install mariadb
brew services start mariadb

echo '------------'
echo 'Install yarn'
echo '------------'
brew install yarn

echo '--------------'
echo 'Install mackup'
echo '--------------'
brew install mackup

echo '---------------------------'
echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Make sure dropbox or iCloud is running first. If you have not backed up via Mackup yet, then run `mackup backup` to symlink preferences for a wide collection of apps to your dropbox. If you already had a backup via mackup run `mackup restore` You'\''ll find more info on Mackup here: https://github.com/lra/mackup.'
echo '2. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '3. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
