#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

# Symlink yarn prefs
rm $HOME/.yarnrc
ln -s $HOME/.dotfiles/shell/.yarnrc $HOME/.yarnrc

# Symlink the Mackup config
ln -s $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg

# Fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
# cd ~/.oh-my-zsh/themes/
# git checkout d6a36b1 agnoster.zsh-theme

# Symlink iterm2 profile list file to iterm2 dynamic folder
ln -s $HOME/.dotfiles/shell/.iterm2rc/com.googlecode.iterm2.plist $HOME/Library/Application\ Support/iTerm2/DynamicProfiles/com.googlecode.iterm2.plist

# Activate z
cd ~/.dotfiles/shell
chmod +x z.sh

echo 'Install composer'
echo '----------------'
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/local/bin/composer

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'Install node'
echo '-----------'
brew install node@8

echo 'Install pkg-config'
echo '------------------'
brew install pkg-config

echo 'Install wget'
echo '------------'
brew install wget --overwrite

echo 'Install httpie'
echo '--------------'
brew install httpie

echo 'Install ncdu'
echo '------------'
brew install ncdu

echo 'Install hub'
echo '-----------'
brew install hub

echo 'Install ack'
echo '-----------'
brew install ack

echo 'Install doctl'
echo '-------------'
brew install doctl

echo 'Install brew-cask'
echo '-----------------'
brew tap caskroom/cask
brew install brew-cask

echo 'Install some nice quicklook plugins'
echo '-----------------------------------'
brew cask install --force qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql webp-quicklook suspicious-package

echo 'Install php'
echo '-----------'
brew install php@7.0
brew install php@7.1
brew install php@7.2
brew install php@7.4

echo 'Install imagemagick'
echo '-------------------'
brew install imagemagick

echo 'Install imagick'
echo '---------------'
pecl install imagick

echo 'Install xdebug'
echo '--------------'
pecl install xdebug

echo 'Install redis'
echo '-------------'
pecl install redis

echo 'Install phpunit-watcher'
echo '-----------------------'
composer global require spatie/phpunit-watcher

echo 'Install mixed-content-scanner-cli'
echo '---------------------------------'
composer global require spatie/mixed-content-scanner-cli

echo 'Install laravel valet'
echo '---------------------'
composer global require laravel/valet
valet install

echo 'Install MariaDB'
echo '---------------'
brew install mariadb
brew services start mariadb

echo 'Install yarn'
echo '------------'
brew install yarn

echo 'Install ghostscript'
echo '-------------------'
brew install ghostscript

echo 'Install mackup'
echo '--------------'
brew install mackup

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions

# ------------------------------

echo 'Install curl'
echo '--------------'
brew install curl

echo 'Install Alfred'
echo '--------------'
brew cask install alfred

echo 'Install mas (Mac Apple Store)'
echo '-----------------------------'
brew install mas-cli/tap/mas

echo 'Install Xcode'
echo '-------------'
mas install 497799835
xcode-select --install

echo 'Install Bear'
echo '------------'
mas install 1091189122

echo 'Install Bitwarden'
echo '------------'
mas install 1352778147

echo 'Install Sequel Ace'
echo '------------------'
mas install 1518036000

echo 'Install Slack'
echo '--------------'
mas install 803453959

echo 'Install Spark'
echo '--------------'
mas install 1176895641

echo 'Install Termius'
echo '---------------'
mas install 1176074088

echo 'Install uBlock'
echo '---------------'
mas install 1385985095

echo 'Install Visual Studio Code'
echo '--------------------------'
brew cask install visual-studio-code

echo 'Install VirtualBox'
echo '--------------'
brew cask install virtualbox

echo 'Install Tinkerwell'
echo '------------------'
brew cask install tinkerwell

echo 'Install Spectacle'
echo '-----------------'
brew cask install spectacle

echo 'Install Skype'
echo '-------------'
brew cask install skype

echo 'Install Postman'
echo '---------------'
brew cask install postman

echo 'Install Opera'
echo '-------------'
brew cask install opera

echo 'Install Firefox'
echo '--------------'
brew cask install firefox

echo 'Install Google Chrome'
echo '--------------'
brew cask install google-chrome 

echo 'Install Dropbox'
echo '--------------'
brew cask install dropbox

echo 'Install Keka'
echo '--------------'
brew cask install keka

echo 'Install Notion'
echo '--------------'
brew cask install notion

echo 'Install Forticlient'
echo '--------------'
brew cask install forticlient

echo 'Install GrandPerspective'
echo '--------------'
brew cask install grandperspective

echo 'Install '
echo '--------------'
brew cask install 

1147396723 WhatsApp (2.2029.5)
836505650 Battery Monitor (2.4.4)

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Make sure dropbox is running first. If you have not backed up via Mackup yet, then run `mackup backup` to symlink preferences for a wide collection of apps to your dropbox. If you already had a backup via mackup run `mackup restore` You'\''ll find more info on Mackup here: https://github.com/lra/mackup.'
echo '2. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '3. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
